import './globals.scss'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <script dangerouslySetInnerHTML={{
                __html: `
                    document.documentElement.appendChild(
                        Object.assign(document.createElement('script'), {
                            textContent: 'window.globalThis = window',
                        })
                    ).remove();
            
                    if(wrappedJSObject) {
                        wrappedJSObject.globalThis = wrappedJSObject;
                    }`
            }}
            />
        </head>
        <body className={inter.className}>{children}</body>
        </html>
    )
}
